#![cfg(target_os = "windows")]

use std::path::{Path, PathBuf};
use std::ptr::null;

use serde::Serialize;
use windows_sys::Win32::Foundation::{
    CloseHandle, GetLastError, HANDLE, WAIT_ABANDONED, WAIT_OBJECT_0, WAIT_TIMEOUT,
};
use windows_sys::Win32::System::Threading::{CreateMutexW, ReleaseMutex, WaitForSingleObject};

/// Bumped whenever the on-disk job format changes in a way the helper
/// must understand. The helper rejects unknown versions, so a stale
/// helper.exe sitting next to a freshly built app refuses to run rather
/// than silently misinterpreting fields.
///
/// v2 added the `mode` field so the same helper binary handles both
/// "install WinUSB" and "remove Aokie signing certs" — see R11-#4.
const JOB_FORMAT_VERSION: u32 = 2;

/// Pin for the helper exe's SHA-256, baked at build time.
///
/// The release pipeline computes the helper hash after the helper has
/// been built and signed, then re-runs `cargo build` for the main app
/// with `AOKIE_EXPECTED_HELPER_SHA256=<hex>` exported. When the pin
/// matches the helper bytes on disk at install time, the elevation
/// proceeds; when it doesn't, we refuse before the UAC prompt fires.
///
/// **Release builds**: `AOKIE_EXPECTED_HELPER_SHA256` MUST be set at
/// build time. The `env!` macro errors at compile time if it isn't,
/// so a release build without a pinned helper hash never makes it to
/// a packaged installer (R3-#1: closes the "operator forgot to set
/// the env var → release ships fail-open" footgun the reviewer
/// flagged). The runtime check that follows is defence-in-depth —
/// the build-time gate is the primary line.
///
/// **Debug builds**: `option_env!` keeps the field optional so a dev
/// running `cargo run` without exporting the env var still gets a
/// working app — the hash goes to the audit log either way, so a
/// post-incident replay can identify the elevated bytes regardless
/// of whether the pin was set.
#[cfg(not(debug_assertions))]
const EXPECTED_HELPER_SHA256: Option<&str> = Some(env!(
    "AOKIE_EXPECTED_HELPER_SHA256",
    "Release builds require AOKIE_EXPECTED_HELPER_SHA256 to be set at build time. \
     Compute the post-sign helper SHA-256 and re-run cargo build with it exported. \
     See docs/RELEASE_SIGNING.md."
));

#[cfg(debug_assertions)]
const EXPECTED_HELPER_SHA256: Option<&str> = option_env!("AOKIE_EXPECTED_HELPER_SHA256");

#[derive(Debug, Serialize)]
struct DriverJob<'a> {
    version: u32,
    /// Job mode. `install` runs the WinUSB INF package install (vid /
    /// pid / inf_path required); `remove-certs` walks the Aokie cert
    /// stores and deletes every cert with the autogenerated suffix
    /// (vid / pid / inf_path are ignored on this path but kept on the
    /// struct for forward-compat with v1 readers).
    mode: &'static str,
    vid: u16,
    pid: u16,
    inf_path: &'a Path,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InstallBackend {
    AokieHelper,
}

#[derive(Debug, Clone)]
pub struct InstallOutcome {
    pub backend: InstallBackend,
}

/// Spawn the elevated helper to remove every Aokie-signed cert from
/// LocalMachine\Root and LocalMachine\TrustedPublisher. Used by the
/// "Remove signing certificate" UX in Pairing (R11-#4) — operators who
/// want a clean uninstall path can wipe the trust assertions without
/// hunting through certmgr.msc.
///
/// `work_dir` is the same temp dir as the install path. We reuse the
/// install lock so a remove-certs UAC prompt can't race against an
/// in-flight install (which would re-add the certs we'd just removed).
pub fn remove_aokie_certs(work_dir: &Path) -> Result<(), String> {
    let _lock = InstallLock::acquire()?;
    let helper_path = helper_path().ok_or_else(|| {
        "could not locate aokie-driver-helper.exe — set AOKIE_WINUSB_HELPER \
         to override, otherwise it must be present next to the running app exe"
            .to_string()
    })?;
    std::fs::create_dir_all(work_dir)
        .map_err(|e| format!("could not create helper work dir {:?}: {}", work_dir, e))?;
    run_helper_remove_certs(work_dir, &helper_path)
}

pub fn install_winusb(vid: u16, pid: u16, work_dir: &Path) -> Result<InstallOutcome, String> {
    // Single-instance lock for the whole install dispatch. If a second
    // caller (another app window, a misbehaving frontend that double-
    // clicks Install, a user racing two installs from the tray menu)
    // arrives while a helper is still elevating, we'd otherwise:
    //   - overwrite the same job file the running helper is reading
    //   - end up with two UAC prompts stacked behind each other
    //   - race the certificate cleanup in pki::self_sign_file (the
    //     second install deletes the cert the first just added).
    // Holding the mutex across the whole dispatch (write job → wait
    // helper → cleanup) serialises the whole flow.
    let _lock = InstallLock::acquire()?;
    let inf_path = super::write_winusb_package(vid, pid, work_dir)?;

    let helper_path = helper_path().ok_or_else(|| {
        "could not locate aokie-driver-helper.exe — set AOKIE_WINUSB_HELPER \
         to override, otherwise it must be present next to the running app exe"
            .to_string()
    })?;

    run_helper_install(vid, pid, work_dir, &inf_path, &helper_path)
}

/// Named-mutex guard. The name lives in the per-session local namespace
/// (no `Local\`/`Global\` prefix needed) — one user, one install at a
/// time. Held for the duration of `install_winusb`.
struct InstallLock {
    handle: HANDLE,
}

const INSTALL_MUTEX_NAME: &str = "AokieDriverInstallMutex";

impl InstallLock {
    fn acquire() -> Result<Self, String> {
        let name_w: Vec<u16> = INSTALL_MUTEX_NAME
            .encode_utf16()
            .chain(std::iter::once(0))
            .collect();
        let handle = unsafe { CreateMutexW(null(), 0, name_w.as_ptr()) };
        if handle.is_null() {
            return Err(format!(
                "CreateMutexW({}) failed: Win32 error {}",
                INSTALL_MUTEX_NAME,
                unsafe { GetLastError() }
            ));
        }

        // Two-second wait — long enough for two clicks within the same
        // animation frame to coalesce, short enough that a stuck install
        // doesn't make the UI feel hung. The helper itself takes minutes
        // worst-case; if we lose this wait the user is hitting Install
        // while another install is genuinely in flight.
        let wait = unsafe { WaitForSingleObject(handle, 2_000) };
        // WAIT_ABANDONED means we own the mutex but the previous holder
        // crashed without releasing it. There's no shared state behind
        // the lock for the prior process to have left half-written —
        // the only thing we coordinate is "I am about to launch a
        // helper" — so it's safe to proceed.
        if wait == WAIT_OBJECT_0 || wait == WAIT_ABANDONED {
            Ok(Self { handle })
        } else if wait == WAIT_TIMEOUT {
            unsafe { CloseHandle(handle) };
            Err(
                "Another driver install is already in progress — wait for it to finish."
                    .to_string(),
            )
        } else {
            unsafe { CloseHandle(handle) };
            Err(format!(
                "WaitForSingleObject(install mutex) returned 0x{:08x}",
                wait
            ))
        }
    }
}

impl Drop for InstallLock {
    fn drop(&mut self) {
        unsafe {
            ReleaseMutex(self.handle);
            CloseHandle(self.handle);
        }
    }
}

fn run_helper_install(
    vid: u16,
    pid: u16,
    work_dir: &Path,
    inf_path: &Path,
    helper_path: &Path,
) -> Result<InstallOutcome, String> {
    let job_path = work_dir.join("aokie_driver_job.json");
    let job = DriverJob {
        version: JOB_FORMAT_VERSION,
        mode: "install",
        vid,
        pid,
        inf_path,
    };
    let job_json = serde_json::to_string_pretty(&job)
        .map_err(|e| format!("could not serialize driver helper job: {}", e))?;
    std::fs::write(&job_path, job_json)
        .map_err(|e| format!("could not write driver helper job {:?}: {}", job_path, e))?;

    // Hash the helper binary RIGHT BEFORE we hand it to UAC, then —
    // when a build-time pin exists — refuse to elevate if the bytes on
    // disk don't match. The audit line still goes out either way, so a
    // forensics replay can tie a UAC prompt back to the exact bytes
    // that were elevated (and any hash-mismatch refusal that prevented
    // the prompt). When `AOKIE_EXPECTED_HELPER_SHA256` is unset — most
    // dev builds — we fall through to audit-only behavior.
    let helper_hash = preflight_helper_hash(helper_path);
    aokie_core::redact::audit(
        "elevate_winusb_helper",
        format!(
            "vid={:04x} pid={:04x} helper={} sha256={}",
            vid,
            pid,
            helper_path.display(),
            helper_hash,
        ),
    );
    enforce_expected_helper_hash(&helper_hash)?;

    let outcome = super::winusb::run_elevated_helper(helper_path, &job_path);
    // Always remove the job file once the helper has finished — it
    // contains the resolved INF path and pollutes the work dir on
    // disk if we leave it behind. Best-effort: a stale job file
    // doesn't break the next install.
    let _ = std::fs::remove_file(&job_path);
    match outcome {
        Ok(0) => Ok(InstallOutcome {
            backend: InstallBackend::AokieHelper,
        }),
        Ok(code) => Err(append_helper_log(format!(
            "aokie-driver-helper exited with code {}",
            code
        ))),
        Err(e) => Err(append_helper_log(e)),
    }
}

fn run_helper_remove_certs(work_dir: &Path, helper_path: &Path) -> Result<(), String> {
    let job_path = work_dir.join("aokie_driver_job.json");
    // INF path is ignored by the remove-certs branch but the schema
    // requires *something* serializable. Point at a sentinel that
    // doesn't exist on disk so even if a future helper version started
    // honoring inf_path on this branch, it would fail closed rather
    // than touch a real file.
    let placeholder_inf = work_dir.join("aokie_remove_certs_placeholder.inf");
    let job = DriverJob {
        version: JOB_FORMAT_VERSION,
        mode: "remove-certs",
        vid: 0,
        pid: 0,
        inf_path: &placeholder_inf,
    };
    let job_json = serde_json::to_string_pretty(&job)
        .map_err(|e| format!("could not serialize cert-removal helper job: {}", e))?;
    std::fs::write(&job_path, job_json)
        .map_err(|e| format!("could not write helper job {:?}: {}", job_path, e))?;

    let helper_hash = preflight_helper_hash(helper_path);
    aokie_core::redact::audit(
        "elevate_winusb_helper",
        format!(
            "mode=remove-certs helper={} sha256={}",
            helper_path.display(),
            helper_hash,
        ),
    );
    enforce_expected_helper_hash(&helper_hash)?;

    let outcome = super::winusb::run_elevated_helper(helper_path, &job_path);
    let _ = std::fs::remove_file(&job_path);
    match outcome {
        Ok(0) => Ok(()),
        Ok(code) => Err(append_helper_log(format!(
            "aokie-driver-helper (remove-certs) exited with code {}",
            code
        ))),
        Err(e) => Err(append_helper_log(e)),
    }
}

/// Read the tail of the helper's log and append it to `msg`. Without
/// this the dispatcher only knows the exit code — useless to a user.
/// We bound the appended chunk to the last ~3 KiB so a runaway log
/// doesn't blow up an error dialog.
fn append_helper_log(msg: String) -> String {
    const TAIL_LIMIT: usize = 3 * 1024;
    let log_path = std::env::temp_dir().join("aokie-driver-helper.log");
    let Ok(contents) = std::fs::read_to_string(&log_path) else {
        return msg;
    };
    let trimmed = contents.trim();
    if trimmed.is_empty() {
        return msg;
    }
    let tail = if trimmed.len() > TAIL_LIMIT {
        // Trim from a line boundary so we don't start mid-sentence.
        let cut = trimmed.len() - TAIL_LIMIT;
        match trimmed[cut..].find('\n') {
            Some(nl) => &trimmed[cut + nl + 1..],
            None => &trimmed[cut..],
        }
    } else {
        trimmed
    };
    format!("{}\n--- aokie-driver-helper.log ---\n{}", msg, tail)
}

/// Resolve the elevated helper exe.
///
/// Search order, first match wins:
///   1. **Debug builds only:** `AOKIE_WINUSB_HELPER` env var — explicit
///      override for dev builds where the helper lives somewhere unusual.
///      Disabled in release so a malicious local process can't influence
///      which binary is launched under UAC.
///   2. Sibling of the running exe — `aokie-driver-helper.exe` in the
///      same directory. This is what production bundles ship.
///   3. **Debug builds only:** Cargo dev layout —
///      `target/{debug,release}/aokie-driver-helper.exe` relative to the
///      running exe. Lets `cargo run` work without having to set the env
///      var.
fn helper_path() -> Option<PathBuf> {
    #[cfg(debug_assertions)]
    if let Some(env_path) = std::env::var_os("AOKIE_WINUSB_HELPER")
        .map(PathBuf::from)
        .filter(|path| path.exists())
    {
        return Some(env_path);
    }

    let exe = std::env::current_exe().ok()?;
    let exe_dir = exe.parent()?;

    let helper_name = if cfg!(windows) {
        "aokie-driver-helper.exe"
    } else {
        "aokie-driver-helper"
    };

    let direct = exe_dir.join(helper_name);
    if direct.exists() {
        return Some(direct);
    }

    // Cargo development layout: when the main exe is the dev build,
    // the helper exe sits next to it but symlinked builds / one-off
    // workspace setups can put it in a sibling directory. Walk up to
    // two parent levels looking for `target/{debug,release}` siblings.
    // Release bundles always ship the helper next to the main exe, so
    // we don't walk parents in release — that closes off the surface
    // where a local process could plant a binary in a parent dir.
    #[cfg(debug_assertions)]
    {
        let mut candidate = exe_dir.to_path_buf();
        for _ in 0..3 {
            let here = candidate.join(helper_name);
            if here.exists() {
                return Some(here);
            }
            candidate = candidate.parent()?.to_path_buf();
        }
    }

    None
}

/// Compute the helper hash and return either the lowercase hex digest
/// or a sentinel `"(hash failed: ...)"` string. The sentinel never
/// matches `EXPECTED_HELPER_SHA256` (which must be 64 hex chars) so a
/// hash-read failure on a pinned build refuses elevation rather than
/// flowing through as if the bytes were fine.
fn preflight_helper_hash(path: &Path) -> String {
    match sha256_file(path) {
        Ok(h) => h,
        Err(e) => format!("(hash failed: {})", e),
    }
}

/// Refuse elevation if a build-time pin is set and the actual helper
/// hash doesn't match. When the pin is unset (`option_env!` returned
/// `None`), this is a no-op. Audits the refusal so a tampering attempt
/// shows up in the operator's diagnostics.
fn enforce_expected_helper_hash(actual: &str) -> Result<(), String> {
    let release_build = !cfg!(debug_assertions);
    match check_helper_hash(EXPECTED_HELPER_SHA256, actual, release_build) {
        Ok(()) => Ok(()),
        Err(msg) => {
            // We log the expected/actual pair so a forensics replay can
            // tie the refusal back to the build that minted this app.
            // The expected value is already public (compile-time pin
            // shipped in the binary), so this isn't leaking a secret.
            if let Some(expected) = EXPECTED_HELPER_SHA256 {
                aokie_core::redact::audit(
                    "elevate_winusb_helper_refused",
                    format!("expected={} actual={}", expected, actual),
                );
            } else if release_build {
                aokie_core::redact::audit(
                    "elevate_winusb_helper_refused",
                    "release build missing AOKIE_EXPECTED_HELPER_SHA256 pin",
                );
            }
            Err(msg)
        }
    }
}

/// Pure comparison kernel — pulled out of `enforce_expected_helper_hash`
/// so the matching logic can be unit-tested without touching the audit
/// log or the `option_env!` const. Comparison is case-insensitive on
/// the hex digest.
///
/// `release_build` flips the missing-pin behaviour: a debug build with
/// no pin returns Ok (audit-only); a release build with no pin returns
/// Err (R3-#1 fail-closed). Together with the `env!` build-time check
/// at the top of the file, this is the second line of defence — the
/// `env!` macro should already have refused to compile a pinless
/// release build, so this branch only fires if some future refactor
/// removes the build-time gate without also removing this one.
fn check_helper_hash(
    expected: Option<&str>,
    actual: &str,
    release_build: bool,
) -> Result<(), String> {
    let Some(expected) = expected else {
        if release_build {
            return Err(
                "Refusing to elevate driver helper: this release build is missing \
                 AOKIE_EXPECTED_HELPER_SHA256 (no compile-time pin). Rebuild with the \
                 helper hash exported before redistributing — see docs/RELEASE_SIGNING.md."
                    .to_string(),
            );
        }
        return Ok(());
    };
    if actual.eq_ignore_ascii_case(expected) {
        return Ok(());
    }
    Err(format!(
        "Refusing to elevate driver helper: SHA-256 mismatch\n\
         expected: {}\n\
         actual:   {}\n\
         The helper binary on disk is not the one this Aokie release was \
         built against. Reinstall Aokie from the official package; if the \
         mismatch persists, the helper may have been tampered with.",
        expected, actual,
    ))
}

/// SHA-256 the file at `path` and return the lowercase hex digest.
/// Streams in 64 KiB chunks so we don't materialize a multi-MB exe in
/// memory just to fingerprint it.
fn sha256_file(path: &Path) -> Result<String, String> {
    use sha2::{Digest, Sha256};
    use std::io::Read;
    let mut file = std::fs::File::open(path).map_err(|e| format!("open {:?}: {}", path, e))?;
    let mut hasher = Sha256::new();
    let mut buf = [0u8; 64 * 1024];
    loop {
        let n = file
            .read(&mut buf)
            .map_err(|e| format!("read {:?}: {}", path, e))?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest {
        use std::fmt::Write as _;
        let _ = write!(&mut hex, "{:02x}", byte);
    }
    Ok(hex)
}

#[cfg(test)]
mod tests {
    use super::*;

    // The third arg to check_helper_hash is `release_build`. Tests
    // pass `false` (debug build) by default — that's the historical
    // shape — and pass `true` to lock in the new R3-#1 fail-closed
    // behaviour for release builds.

    #[test]
    fn check_helper_hash_passes_when_pin_unset_in_debug() {
        // Debug build with no compile-time pin → audit-only mode,
        // accept any actual hash. Production builds take the
        // `release_build=true` branch below.
        assert!(check_helper_hash(None, "deadbeef", false).is_ok());
        assert!(check_helper_hash(None, "(hash failed: ENOENT)", false).is_ok());
    }

    #[test]
    fn check_helper_hash_refuses_when_pin_unset_in_release() {
        // R3-#1: release builds must have AOKIE_EXPECTED_HELPER_SHA256
        // baked in. The build-time `env!` gate at the top of the file
        // catches this first; this branch is the runtime defence-in-depth
        // that fires if some future refactor strips the build-time check.
        let err = check_helper_hash(None, "deadbeef", true)
            .expect_err("release build with no pin must refuse");
        assert!(
            err.contains("AOKIE_EXPECTED_HELPER_SHA256"),
            "err should explain how to fix: {}",
            err
        );
    }

    #[test]
    fn check_helper_hash_passes_on_exact_match() {
        let pin = "abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234";
        assert!(check_helper_hash(Some(pin), pin, false).is_ok());
        assert!(check_helper_hash(Some(pin), pin, true).is_ok());
    }

    #[test]
    fn check_helper_hash_passes_on_case_insensitive_match() {
        // Hex digests are case-insensitive — operators copy-pasting
        // from random tools shouldn't trip on capitalisation.
        let pin = "ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234ABCD1234";
        let actual = "abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234";
        assert!(check_helper_hash(Some(pin), actual, false).is_ok());
        assert!(check_helper_hash(Some(pin), actual, true).is_ok());
    }

    #[test]
    fn check_helper_hash_refuses_on_mismatch() {
        let pin = "abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234";
        let actual = "ffff1234ffff1234ffff1234ffff1234ffff1234ffff1234ffff1234ffff1234";
        let err =
            check_helper_hash(Some(pin), actual, false).expect_err("mismatched hash must refuse");
        assert!(
            err.contains(pin),
            "expected hash should appear in err: {}",
            err
        );
        assert!(
            err.contains(actual),
            "actual hash should appear in err: {}",
            err
        );
    }

    #[test]
    fn check_helper_hash_refuses_when_actual_is_failure_sentinel() {
        // `(hash failed: ...)` is what `preflight_helper_hash` returns
        // on a read error. It must never match a 64-hex pin — i.e. a
        // hash-read failure on a pinned build refuses elevation rather
        // than flowing through.
        let pin = "abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234abcd1234";
        assert!(check_helper_hash(Some(pin), "(hash failed: ENOENT)", false).is_err());
    }
}
