#![cfg(target_os = "windows")]

use std::mem::{size_of, zeroed};
use std::path::Path;
use std::ptr::{null, null_mut};

use chrono::Datelike;

use windows_sys::Win32::Devices::DeviceAndDriverInstallation::{
    CM_Get_DevNode_Status, CM_Get_Parent, CM_Query_And_Remove_SubTreeW, CM_Reenumerate_DevNode,
    SetupCloseInfFile, SetupCopyOEMInfW, SetupDiDestroyDeviceInfoList, SetupDiEnumDeviceInfo,
    SetupDiGetClassDevsW, SetupDiGetDeviceRegistryPropertyW, SetupDiSetDeviceRegistryPropertyW,
    SetupOpenInfFileW, UpdateDriverForPlugAndPlayDevicesW, CM_REENUMERATE_RETRY_INSTALLATION,
    CM_REMOVE_NO_RESTART, CONFIGFLAG_REINSTALL, CR_NO_SUCH_DEVNODE, CR_SUCCESS, DIGCF_ALLCLASSES,
    DIGCF_PRESENT, HDEVINFO, INF_STYLE_WIN4, INSTALLFLAG_FORCE, SPDRP_CONFIGFLAGS, SPDRP_HARDWAREID,
    SPOST_PATH, SP_COPY_NEWER_OR_SAME, SP_DEVINFO_DATA,
};
use windows_sys::Win32::Foundation::{
    CloseHandle, GetLastError, ERROR_INSUFFICIENT_BUFFER, ERROR_NO_MORE_ITEMS, HANDLE, WAIT_FAILED,
    WAIT_OBJECT_0, WAIT_TIMEOUT,
};
use windows_sys::Win32::System::Registry::REG_MULTI_SZ;
use windows_sys::Win32::System::Threading::{GetExitCodeProcess, WaitForSingleObject};
use windows_sys::Win32::UI::Shell::{ShellExecuteExW, SEE_MASK_NOCLOSEPROCESS, SHELLEXECUTEINFOW};
use windows_sys::Win32::UI::WindowsAndMessaging::SW_SHOWNORMAL;

pub const INF_NAME: &str = "aokie_winusb_bluetooth.inf";
pub const CAT_NAME: &str = "aokie_winusb_bluetooth.cat";
const DRIVER_CLASS_GUID: &str = "{88BAE032-5A81-49f0-BC3D-A4FF138216D6}";
const AOKIE_INTERFACE_GUID: &str = "{B6F5F3A8-6E2C-41D8-9B7A-6E35F60480D6}";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WinusbPackage {
    vid: u16,
    pid: u16,
    description: String,
    /// Free-form `MM/DD/YYYY,major.minor.build.rev` string for the
    /// INF's `DriverVer`. Defaulted to today's date so re-running the
    /// installer always supersedes whatever's already in the driver
    /// store — without this, repeat installs were no-ops because
    /// Windows treats identical DriverVer as "no newer version".
    driver_ver: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstallResult {
    pub reboot_required: bool,
}

impl WinusbPackage {
    pub fn new(vid: u16, pid: u16, description: &str) -> Self {
        Self {
            vid,
            pid,
            description: sanitize_inf_string(description),
            driver_ver: default_driver_ver(),
        }
    }

    /// Override `DriverVer` for tests that pin a fixture string. Production
    /// callers should let the constructor derive it from today's date.
    #[cfg(test)]
    pub fn with_driver_ver(mut self, value: &str) -> Self {
        self.driver_ver = value.to_string();
        self
    }

    pub fn hardware_id(&self) -> String {
        hardware_id(self.vid, self.pid)
    }

    pub fn render_inf(&self) -> String {
        let hardware_id = self.hardware_id();
        format!(
            r#"; Generated by Aokie for a selected Bluetooth dongle.
; The function driver is Windows' in-box WinUSB service.

[Version]
Signature="$Windows NT$"
Class=USBDevice
ClassGuid={class_guid}
Provider=%ProviderName%
DriverVer={driver_ver}
CatalogFile={cat_name}

[ClassInstall32]
AddReg=AokieClassReg

[AokieClassReg]
HKR,,,0,"Universal Serial Bus devices"
HKR,,Icon,,-20

[Manufacturer]
%ProviderName%=AokieDevices,NTx86,NTamd64,NTarm64

[AokieDevices.NTx86]
%DeviceName%=WinUSB_Install,{hardware_id}

[AokieDevices.NTamd64]
%DeviceName%=WinUSB_Install,{hardware_id}

[AokieDevices.NTarm64]
%DeviceName%=WinUSB_Install,{hardware_id}

[WinUSB_Install]
Include=winusb.inf
Needs=WINUSB.NT

[WinUSB_Install.Services]
AddService=WinUSB,0x00000002,WinUSB_ServiceInstall

[WinUSB_ServiceInstall]
DisplayName="WinUSB - Aokie Bluetooth"
ServiceType=1
StartType=3
ErrorControl=1
ServiceBinary=%12%\WinUSB.sys

[WinUSB_Install.Wdf]
KmdfService=WINUSB, WinUsb_Install

[WinUsb_Install]
KmdfLibraryVersion=1.11

[WinUSB_Install.HW]
AddReg=DeviceInterfaceGUIDs

[DeviceInterfaceGUIDs]
HKR,,DeviceInterfaceGUIDs,0x10000,"{interface_guid}"

[Strings]
ProviderName="Aokie"
DeviceName="{device_name}"
"#,
            class_guid = DRIVER_CLASS_GUID,
            hardware_id = hardware_id,
            interface_guid = AOKIE_INTERFACE_GUID,
            device_name = self.description,
            driver_ver = self.driver_ver,
            cat_name = CAT_NAME,
        )
    }
}

/// `DriverVer` derived from the current local date. The build number
/// goes `YYYY*100 + month*1`-style so each daily build still increments
/// monotonically — Windows compares `DriverVer` lexically, so a
/// monotonically increasing fourth field is enough to make repeat
/// installs replace older copies.
fn default_driver_ver() -> String {
    let now = chrono::Local::now().naive_local().date();
    let revision = (now.year() as u32) * 10_000 + (now.month0() + 1) * 100 + (now.day0() + 1);
    format!(
        "{:02}/{:02}/{:04},2.2.0.{}",
        now.month0() + 1,
        now.day0() + 1,
        now.year(),
        revision,
    )
}

pub fn hardware_id(vid: u16, pid: u16) -> String {
    format!("USB\\VID_{:04X}&PID_{:04X}", vid, pid)
}

pub fn sanitize_inf_string(value: &str) -> String {
    let sanitized: String = value
        .chars()
        .filter_map(|ch| match ch {
            '\r' | '\n' | '\t' => Some(' '),
            '"' => None,
            ch if ch.is_control() => None,
            ch => Some(ch),
        })
        .collect();
    let trimmed = sanitized.split_whitespace().collect::<Vec<_>>().join(" ");
    if trimmed.is_empty() {
        "Aokie Bluetooth Dongle".to_string()
    } else {
        trimmed
    }
}

pub fn install_package(inf_path: &Path, vid: u16, pid: u16) -> Result<InstallResult, String> {
    let full_inf_path = inf_path
        .canonicalize()
        .map_err(|e| format!("could not canonicalize INF path {:?}: {}", inf_path, e))?;
    let hwid = hardware_id(vid, pid);

    // Pre-flight: parse the rendered INF before staging anything. If
    // we got the format wrong, SetupOpenInfFileW reports the failing
    // line via *errorline; SetupCopyOEMInfW would otherwise just
    // return a generic ERROR_INVALID_DATA / ERROR_WRONG_INF_STYLE and
    // we'd be guessing. Failing here also avoids leaving a half-staged
    // INF in the driver store.
    parse_inf_or_describe(&full_inf_path)?;

    // Generate + self-sign the catalog before SetupCopyOEMInfW. The
    // INF references it by name (CatalogFile=...), and Windows 10/11
    // refuse to install drivers without a valid signed cat.
    super::pki::create_and_sign_cat(&full_inf_path, &hwid)
        .map_err(|e| format!("CAT generation/signing failed: {}", e))?;

    let inf_w = wide_null(&full_inf_path.to_string_lossy());
    let media_dir = full_inf_path
        .parent()
        .ok_or_else(|| format!("INF path {:?} has no parent directory", full_inf_path))?;
    let media_w = wide_null(&media_dir.to_string_lossy());

    unsafe {
        if SetupCopyOEMInfW(
            inf_w.as_ptr(),
            media_w.as_ptr(),
            SPOST_PATH,
            SP_COPY_NEWER_OR_SAME,
            null_mut(),
            0,
            null_mut(),
            null_mut(),
        ) == 0
        {
            let err = GetLastError();
            return Err(format!(
                "SetupCopyOEMInfW failed for {:?}: {}",
                full_inf_path,
                describe_setup_error(err),
            ));
        }

        let mut reboot_required = 0;
        let hwid_w = wide_null(&hwid);
        if UpdateDriverForPlugAndPlayDevicesW(
            null_mut(),
            hwid_w.as_ptr(),
            inf_w.as_ptr(),
            INSTALLFLAG_FORCE,
            &mut reboot_required,
        ) == 0
        {
            let err = GetLastError();
            // ERROR_NO_SUCH_DEVINST (0xE000020B) and ERROR_NO_MORE_ITEMS
            // (259) both mean "no plugged-in device matched the hardware
            // ID". That's not actually a failure — the SetupCopyOEMInfW
            // above already added the INF to the driver store, so the
            // device picks it up on next plug-in. libwdi's installer
            // makes the same distinction via process_error returning
            // WDI_SUCCESS for ERROR_NO_SUCH_DEVINST.
            const ERROR_NO_SUCH_DEVINST: u32 = 0xE000_020B;
            if err != ERROR_NO_MORE_ITEMS && err != ERROR_NO_SUCH_DEVINST {
                return Err(format!(
                    "UpdateDriverForPlugAndPlayDevicesW failed for {}: {}",
                    hwid,
                    describe_setup_error(err),
                ));
            }
            // Fall through — INF is staged, device will bind when plugged.
        }

        // Clean up CONFIGFLAG_REINSTALL on the present device. Older
        // versions of `flag_phantom_devices_for_reinstall` ORed this
        // flag onto every matching DEVINST without a phantom-only
        // filter, including the device we just successfully bound.
        // CONFIGFLAG_REINSTALL tells PnP to redo driver search on
        // next enumeration, and without an INSTALLFLAG_FORCE in that
        // re-search Windows picks the highest-ranked INF — which on
        // signature trust is Microsoft-signed BTHUSB, not our
        // self-signed driver. So users running the old installer
        // saw the binding "evaporate" on unplug+replug. This step
        // unsticks them: clear REINSTALL on present matches so
        // future replugs keep our driver. Phantom devices keep
        // their REINSTALL flag (refreshing them next plug-in is
        // intentional).
        let _ = clear_reinstall_flag_on_present_devices(&hwid);

        // Force the device to re-bind without unplug. Mirrors libwdi's
        // post-install `enumerate_device` step. If the device isn't
        // currently plugged in this is a no-op (logged but not fatal).
        let _ = reenumerate_device(&hwid);

        // Walk the USB tree for phantom devices that match our HWID
        // and flag them for reinstall on the next plug-in. This
        // catches the "user previously bound to BTHUSB, dongle is
        // now unplugged" case so the next reconnect picks up our
        // driver instead of cached state. Phantom-only — the
        // currently-present device is left untouched.
        let _ = flag_phantom_devices_for_reinstall(&hwid);

        Ok(InstallResult {
            reboot_required: reboot_required != 0,
        })
    }
}

/// Parse `inf_path` via SetupOpenInfFileW and immediately close it. The
/// goal is purely diagnostic: SetupCopyOEMInfW will reject a malformed
/// INF, but only with a generic Win32 code; the SetupAPI parser, by
/// contrast, fills `errorline` with the offending line number when
/// something doesn't tokenise. Catching it here gives the user (and us
/// if we ever break the renderer) an actionable message.
fn parse_inf_or_describe(inf_path: &Path) -> Result<(), String> {
    let inf_w = wide_null(&inf_path.to_string_lossy());
    let mut error_line: u32 = 0;
    let h = unsafe { SetupOpenInfFileW(inf_w.as_ptr(), null(), INF_STYLE_WIN4, &mut error_line) };
    if h.is_null() || h as isize == -1 {
        let err = unsafe { GetLastError() };
        if error_line != 0 {
            return Err(format!(
                "INF parse failed at line {}: {}",
                error_line,
                describe_setup_error(err),
            ));
        }
        return Err(format!(
            "SetupOpenInfFileW({:?}) failed: {}",
            inf_path,
            describe_setup_error(err),
        ));
    }
    unsafe {
        SetupCloseInfFile(h);
    }
    Ok(())
}

/// Map the SetupAPI / Win32 error codes the install flow can return
/// to actionable messages. Mirrors libwdi's `process_error` table; the
/// raw code is appended so a developer can still cross-reference.
pub fn describe_setup_error(err: u32) -> String {
    let msg = match err {
        // Plain Win32
        2 | 3 => "the system cannot find the file or path specified", // ERROR_FILE_NOT_FOUND / ERROR_PATH_NOT_FOUND
        5 => "access denied — this process needs to be run as administrator",
        13 => "invalid data — the INF is missing required fields", // ERROR_INVALID_DATA
        87 => "invalid parameter — typically a malformed hardware ID or INF path",
        183 => "the driver is already installed for this hardware ID", // ERROR_ALREADY_EXISTS
        259 => "no more entries — UpdateDriverForPlugAndPlayDevicesW found no matching devices", // ERROR_NO_MORE_ITEMS
        1058 => "the Windows Update service is disabled — please enable it",
        // SetupAPI errors live in 0xE0000xxx
        0xE000_0203 => "no compatible driver — INF has no section for this Windows architecture",
        0xE000_0217 => "INF service section references a non-present .sys",
        0xE000_022F => {
            "system policy refuses unsigned drivers — enable test signing or accept the cert"
        }
        0xE000_0235 => "tried to use a 32-bit installer on a 64-bit machine",
        0xE000_023F => "user cancelled at the trusted-publisher warning",
        0xE000_0243 => "Windows refused to trust the installed certificate",
        0xE000_0246 => "another driver installer is currently running — wait for it to finish",
        0xE000_0247 => "user declined the unsigned-driver warning",
        0xE000_024B => "INF's CAT file hashes don't match — regenerate and re-sign the catalog",
        0xE000_0304 => "unable to locate the CAT file referenced by the INF",
        0x800B_0100 => "INF style mismatch — usually a missing CatalogFile= entry",
        // Windows Update specific
        0x8024_002E => "Windows Update is disabled — enable the service to install drivers",
        _ => return format!("Win32 error {0} (0x{0:08x})", err),
    };
    format!("{} (Win32 error {} / 0x{:08x})", msg, err, err)
}

/// Tell PnP to re-enumerate the device tree subtree rooted at the
/// node matching `hardware_id`. If the device isn't currently present
/// this returns Ok(()) without doing anything — that's the libwdi
/// behaviour and matches user expectation (the install copies the
/// driver into the store; the device picks it up next time it's
/// connected).
pub fn reenumerate_device(hardware_id: &str) -> Result<(), String> {
    // CM_Locate_DevNodeW takes a device-INSTANCE id, not a hardware id.
    // The instance id has the form `USB\VID_xxxx&PID_xxxx\<instance>`
    // and varies per physical plug-in; the hardware id is just the
    // VID/PID prefix and is the same for every instance. Passing the
    // hardware id here always returns CR_NO_SUCH_DEVNODE — which is
    // exactly the silent no-op libwdi did NOT have, since libwdi
    // tracked the device-instance id from the upstream enumeration
    // and passed it explicitly. Without a successful re-enumerate
    // post-install, the device keeps using whatever driver was bound
    // before (Zadig's libwdi-INF, BTHUSB, the previous Aokie INF) —
    // which we suspect is breaking SCO bring-up because the iso pipes
    // are armed against the wrong driver's runtime state.
    //
    // Walk the present USB device set, find every node whose hardware
    // id list contains ours, and CM_Reenumerate_DevNode each. Mirrors
    // libwdi's `enumerate_device(device_id)` step that ran after a
    // successful UpdateDriverForPlugAndPlayDevices / SetupCopyOEMInf.
    let enumerator = wide_null("USB");
    let info_set = unsafe {
        SetupDiGetClassDevsW(
            null(),
            enumerator.as_ptr(),
            null_mut(),
            DIGCF_ALLCLASSES | DIGCF_PRESENT,
        )
    };
    if info_set == windows_sys::Win32::Foundation::INVALID_HANDLE_VALUE as HDEVINFO {
        return Err(format!(
            "SetupDiGetClassDevsW(USB, ALLCLASSES|PRESENT) failed: Win32 error {}",
            unsafe { GetLastError() }
        ));
    }
    let _info_set_guard = DeviceInfoSetGuard(info_set);

    let target_upper = hardware_id.to_ascii_uppercase();
    let mut reenum_attempts = 0usize;
    let mut reenum_ok = 0usize;
    let mut index: u32 = 0;
    loop {
        let mut info: SP_DEVINFO_DATA = unsafe { zeroed() };
        info.cbSize = size_of::<SP_DEVINFO_DATA>() as u32;
        if unsafe { SetupDiEnumDeviceInfo(info_set, index, &mut info) } == 0 {
            if unsafe { GetLastError() } == ERROR_NO_MORE_ITEMS {
                break;
            }
            index += 1;
            continue;
        }
        index += 1;

        let hw_ids = read_multi_sz(info_set, &info, SPDRP_HARDWAREID);
        let matches = hw_ids
            .iter()
            .any(|id| id.to_ascii_uppercase().contains(&target_upper));
        if !matches {
            continue;
        }

        reenum_attempts += 1;
        let cr = unsafe { CM_Reenumerate_DevNode(info.DevInst, CM_REENUMERATE_RETRY_INSTALLATION) };
        if cr == CR_SUCCESS {
            reenum_ok += 1;
        }
    }

    if reenum_attempts == 0 {
        // No matching device currently present. Not an error — the
        // install already staged the INF into the driver store, and
        // the device will pick it up next plug-in. Same outcome as
        // libwdi's `enumerate_device` returning early on a missing
        // device_id.
        return Ok(());
    }
    if reenum_ok == 0 {
        return Err(format!(
            "CM_Reenumerate_DevNode failed for all {} matching device(s)",
            reenum_attempts
        ));
    }
    Ok(())
}

/// Full software "virtual replug": for every present USB device whose
/// hardware-id list contains `hardware_id`, get its parent, query-and-remove
/// the device (surprise removal), then re-enumerate the parent so PnP re-adds
/// it fresh. This resets the isochronous endpoint state that a COLD BOOT leaves
/// dead (SCO transfers come back empty until a physical unplug/replug) — a
/// stronger reset than `CM_Reenumerate_DevNode` on the device alone, which some
/// dongles reject. Best-effort: a not-present device is `Ok`, and a per-device
/// veto is logged and skipped. MUST be called with no open handle on the device
/// (i.e. before the WinUSB interface is opened).
pub fn restart_device(hardware_id: &str) -> Result<(), String> {
    let enumerator = wide_null("USB");
    let info_set = unsafe {
        SetupDiGetClassDevsW(
            null(),
            enumerator.as_ptr(),
            null_mut(),
            DIGCF_ALLCLASSES | DIGCF_PRESENT,
        )
    };
    if info_set == windows_sys::Win32::Foundation::INVALID_HANDLE_VALUE as HDEVINFO {
        return Err(format!(
            "SetupDiGetClassDevsW(USB, ALLCLASSES|PRESENT) failed: Win32 error {}",
            unsafe { GetLastError() }
        ));
    }
    let _info_set_guard = DeviceInfoSetGuard(info_set);

    let target_upper = hardware_id.to_ascii_uppercase();
    let mut attempts = 0usize;
    let mut restarted = 0usize;
    let mut index: u32 = 0;
    loop {
        let mut info: SP_DEVINFO_DATA = unsafe { zeroed() };
        info.cbSize = size_of::<SP_DEVINFO_DATA>() as u32;
        if unsafe { SetupDiEnumDeviceInfo(info_set, index, &mut info) } == 0 {
            if unsafe { GetLastError() } == ERROR_NO_MORE_ITEMS {
                break;
            }
            index += 1;
            continue;
        }
        index += 1;

        let hw_ids = read_multi_sz(info_set, &info, SPDRP_HARDWAREID);
        if !hw_ids
            .iter()
            .any(|id| id.to_ascii_uppercase().contains(&target_upper))
        {
            continue;
        }

        attempts += 1;
        // Grab the parent first — we re-enumerate it after the child is gone.
        let mut parent: u32 = 0;
        let have_parent = unsafe { CM_Get_Parent(&mut parent, info.DevInst, 0) } == CR_SUCCESS;
        // Surprise-remove the device (null veto out-params: we don't inspect the
        // veto, a non-success return is enough to skip).
        let cr = unsafe {
            CM_Query_And_Remove_SubTreeW(info.DevInst, null_mut(), null_mut(), 0, CM_REMOVE_NO_RESTART)
        };
        if cr != CR_SUCCESS {
            eprintln!(
                "[AokieDongle] restart_device: query-and-remove failed/vetoed (cr={})",
                cr
            );
            continue;
        }
        // Re-add: re-enumerate the parent hub (fallback: the node itself) so PnP
        // rediscovers the device with fresh descriptors + iso endpoint state.
        let reenum_target = if have_parent && parent != 0 {
            parent
        } else {
            info.DevInst
        };
        if unsafe { CM_Reenumerate_DevNode(reenum_target, CM_REENUMERATE_RETRY_INSTALLATION) }
            == CR_SUCCESS
        {
            restarted += 1;
        }
    }

    if attempts == 0 {
        return Ok(());
    }
    if restarted == 0 {
        return Err(format!(
            "restart_device: no matching device could be restarted ({} matched)",
            attempts
        ));
    }
    Ok(())
}

/// Clear `CONFIGFLAG_REINSTALL` on every currently-present USB device
/// whose hardware-id list contains `target_hardware_id`. Used to
/// repair the "install doesn't persist across replugs" bug introduced
/// by the previous unfiltered `flag_phantom_devices_for_reinstall`.
///
/// CONFIGFLAG_REINSTALL on a present device causes PnP to redo driver
/// search on the next plug-in, and the re-search ignores the binding
/// our installer just forced — Windows picks Microsoft-signed BTHUSB
/// over our self-signed INF on signature trust. Clearing the flag
/// after a successful install means the device's "current driver"
/// registry entry sticks across unplug/replug.
pub fn clear_reinstall_flag_on_present_devices(target_hardware_id: &str) -> Result<usize, String> {
    let enumerator = wide_null("USB");
    let info_set = unsafe {
        SetupDiGetClassDevsW(
            null(),
            enumerator.as_ptr(),
            null_mut(),
            DIGCF_ALLCLASSES | DIGCF_PRESENT,
        )
    };
    if info_set == windows_sys::Win32::Foundation::INVALID_HANDLE_VALUE as HDEVINFO {
        return Err(format!(
            "SetupDiGetClassDevsW(USB, ALLCLASSES|PRESENT) failed: Win32 error {}",
            unsafe { GetLastError() }
        ));
    }
    let _info_set_guard = DeviceInfoSetGuard(info_set);

    let target_upper = target_hardware_id.to_ascii_uppercase();
    let mut cleared = 0usize;
    let mut index: u32 = 0;
    loop {
        let mut info: SP_DEVINFO_DATA = unsafe { zeroed() };
        info.cbSize = size_of::<SP_DEVINFO_DATA>() as u32;
        if unsafe { SetupDiEnumDeviceInfo(info_set, index, &mut info) } == 0 {
            if unsafe { GetLastError() } == ERROR_NO_MORE_ITEMS {
                break;
            }
            index += 1;
            continue;
        }
        index += 1;

        let hw_ids = read_multi_sz(info_set, &info, SPDRP_HARDWAREID);
        let matches = hw_ids
            .iter()
            .any(|id| id.to_ascii_uppercase().contains(&target_upper));
        if !matches {
            continue;
        }

        let mut config_flags: u32 = 0;
        let mut reg_type: u32 = 0;
        let mut size: u32 = size_of::<u32>() as u32;
        if unsafe {
            SetupDiGetDeviceRegistryPropertyW(
                info_set,
                &info,
                SPDRP_CONFIGFLAGS,
                &mut reg_type,
                &mut config_flags as *mut _ as *mut u8,
                size,
                &mut size,
            )
        } == 0
        {
            // No CONFIGFLAGS to clear.
            continue;
        }
        if config_flags & CONFIGFLAG_REINSTALL == 0 {
            // Already clean; nothing to write back.
            continue;
        }
        config_flags &= !CONFIGFLAG_REINSTALL;
        if unsafe {
            SetupDiSetDeviceRegistryPropertyW(
                info_set,
                &mut info,
                SPDRP_CONFIGFLAGS,
                &config_flags as *const _ as *const u8,
                size_of::<u32>() as u32,
            )
        } != 0
        {
            cleared += 1;
        }
    }
    Ok(cleared)
}

/// Walk all known USB devices (present AND phantom). For every PHANTOM
/// entry whose hardware-id list contains `target_hardware_id`, OR
/// `CONFIGFLAG_REINSTALL` into its `SPDRP_CONFIGFLAGS`. Mirrors
/// libwdi's `check_removed`.
///
/// **Phantom-only filter is critical.** Without `CM_Get_DevNode_Status`
/// gating, this function ORs `CONFIGFLAG_REINSTALL` on the currently-
/// present device too — which we just bound to our WinUSB INF via
/// `UpdateDriverForPlugAndPlayDevicesW(INSTALLFLAG_FORCE)`. The REINSTALL
/// flag tells PnP to redo driver search on the next plug-in, and without
/// the FORCE flag in that re-search Windows picks whichever INF ranks
/// highest by signature trust — which is Microsoft-signed BTHUSB.SYS,
/// not our self-signed Aokie INF. Net effect: the user runs Install,
/// Device Manager shows the WinUSB binding, they unplug + replug, and
/// the dongle reverts to BTHUSB. Setting the flag on phantoms is fine
/// (those bindings are stale; refreshing them is the goal); setting it
/// on the present device is what causes the "install doesn't persist"
/// bug.
pub fn flag_phantom_devices_for_reinstall(target_hardware_id: &str) -> Result<usize, String> {
    let enumerator = wide_null("USB");
    let info_set = unsafe {
        SetupDiGetClassDevsW(
            null(),
            enumerator.as_ptr(),
            null_mut(),
            DIGCF_ALLCLASSES, // intentionally NOT DIGCF_PRESENT — we need to see phantoms
        )
    };
    if info_set == windows_sys::Win32::Foundation::INVALID_HANDLE_VALUE as HDEVINFO {
        return Err(format!(
            "SetupDiGetClassDevsW(USB, ALLCLASSES) failed: Win32 error {}",
            unsafe { GetLastError() }
        ));
    }
    let _info_set_guard = DeviceInfoSetGuard(info_set);

    let target_upper = target_hardware_id.to_ascii_uppercase();
    let mut flagged = 0usize;
    let mut index: u32 = 0;
    loop {
        let mut info: SP_DEVINFO_DATA = unsafe { zeroed() };
        info.cbSize = size_of::<SP_DEVINFO_DATA>() as u32;
        if unsafe { SetupDiEnumDeviceInfo(info_set, index, &mut info) } == 0 {
            if unsafe { GetLastError() } == ERROR_NO_MORE_ITEMS {
                break;
            }
            // Other enumeration errors aren't worth aborting the whole
            // walk for — skip to next index.
            index += 1;
            continue;
        }
        index += 1;

        // Pull the hardware-id list and check whether ours is in it.
        let hw_ids = read_multi_sz(info_set, &info, SPDRP_HARDWAREID);
        let matches = hw_ids
            .iter()
            .any(|id| id.to_ascii_uppercase().contains(&target_upper));
        if !matches {
            continue;
        }

        // Phantom-only: only act on devices that are not currently
        // present. CM_Get_DevNode_Status returning CR_NO_SUCH_DEVNODE
        // is the unambiguous signal that this DEVINST is a phantom
        // (in the registry but no live device behind it). Anything
        // else — CR_SUCCESS or any other code — means the device IS
        // currently enumerated, and we must NOT touch its CONFIGFLAGS.
        let mut status: u32 = 0;
        let mut problem: u32 = 0;
        let cr = unsafe { CM_Get_DevNode_Status(&mut status, &mut problem, info.DevInst, 0) };
        if cr != CR_NO_SUCH_DEVNODE {
            continue;
        }

        // Read existing CONFIGFLAGS and OR in REINSTALL. We never
        // clear; if it was already set, this is a no-op.
        let mut config_flags: u32 = 0;
        let mut reg_type: u32 = 0;
        let mut size: u32 = size_of::<u32>() as u32;
        if unsafe {
            SetupDiGetDeviceRegistryPropertyW(
                info_set,
                &info,
                SPDRP_CONFIGFLAGS,
                &mut reg_type,
                &mut config_flags as *mut _ as *mut u8,
                size,
                &mut size,
            )
        } == 0
        {
            // No existing CONFIGFLAGS value — start from zero.
            config_flags = 0;
        }
        config_flags |= CONFIGFLAG_REINSTALL;
        if unsafe {
            SetupDiSetDeviceRegistryPropertyW(
                info_set,
                &mut info,
                SPDRP_CONFIGFLAGS,
                &config_flags as *const _ as *const u8,
                size_of::<u32>() as u32,
            )
        } != 0
        {
            flagged += 1;
        }
    }
    Ok(flagged)
}

/// AOK-DRIVER-001 restore: revert a device Aokie bound to WinUSB back to
/// its in-box driver (e.g. BTHUSB). Mechanism: set `CONFIGFLAG_REINSTALL`
/// on every present device matching `hwid`, then re-enumerate. Without an
/// `INSTALLFLAG_FORCE` in that PnP re-search, Windows re-ranks the
/// candidate INFs by signature trust and picks Microsoft-signed BTHUSB
/// over our self-signed WinUSB INF — which is exactly the revert we want.
/// (This is the mirror image of the "install doesn't persist" bug the
/// `clear_reinstall_flag_on_present_devices` path guards against.)
pub fn restore_inbox_driver(vid: u16, pid: u16) -> Result<(), String> {
    let hwid = hardware_id(vid, pid);
    let flagged = set_reinstall_flag_on_present_devices(&hwid)?;
    if flagged == 0 {
        return Err(format!(
            "no present {} device to restore — plug the dongle in and retry",
            hwid
        ));
    }
    // Best-effort re-search; a not-present device is a no-op.
    let _ = reenumerate_device(&hwid);
    Ok(())
}

/// OR `CONFIGFLAG_REINSTALL` into every PRESENT device matching
/// `target_hardware_id` (the inverse of
/// `clear_reinstall_flag_on_present_devices`). Used only by
/// [`restore_inbox_driver`].
fn set_reinstall_flag_on_present_devices(target_hardware_id: &str) -> Result<usize, String> {
    let enumerator = wide_null("USB");
    let info_set = unsafe {
        SetupDiGetClassDevsW(
            null(),
            enumerator.as_ptr(),
            null_mut(),
            DIGCF_ALLCLASSES | DIGCF_PRESENT,
        )
    };
    if info_set == windows_sys::Win32::Foundation::INVALID_HANDLE_VALUE as HDEVINFO {
        return Err(format!(
            "SetupDiGetClassDevsW(USB, ALLCLASSES|PRESENT) failed: Win32 error {}",
            unsafe { GetLastError() }
        ));
    }
    let _info_set_guard = DeviceInfoSetGuard(info_set);

    let target_upper = target_hardware_id.to_ascii_uppercase();
    let mut flagged = 0usize;
    let mut index: u32 = 0;
    loop {
        let mut info: SP_DEVINFO_DATA = unsafe { zeroed() };
        info.cbSize = size_of::<SP_DEVINFO_DATA>() as u32;
        if unsafe { SetupDiEnumDeviceInfo(info_set, index, &mut info) } == 0 {
            if unsafe { GetLastError() } == ERROR_NO_MORE_ITEMS {
                break;
            }
            index += 1;
            continue;
        }
        index += 1;

        let hw_ids = read_multi_sz(info_set, &info, SPDRP_HARDWAREID);
        if !hw_ids
            .iter()
            .any(|id| id.to_ascii_uppercase().contains(&target_upper))
        {
            continue;
        }

        let mut config_flags: u32 = 0;
        let mut reg_type: u32 = 0;
        let mut size: u32 = size_of::<u32>() as u32;
        if unsafe {
            SetupDiGetDeviceRegistryPropertyW(
                info_set,
                &info,
                SPDRP_CONFIGFLAGS,
                &mut reg_type,
                &mut config_flags as *mut _ as *mut u8,
                size,
                &mut size,
            )
        } == 0
        {
            config_flags = 0;
        }
        config_flags |= CONFIGFLAG_REINSTALL;
        if unsafe {
            SetupDiSetDeviceRegistryPropertyW(
                info_set,
                &mut info,
                SPDRP_CONFIGFLAGS,
                &config_flags as *const _ as *const u8,
                size_of::<u32>() as u32,
            )
        } != 0
        {
            flagged += 1;
        }
    }
    Ok(flagged)
}

/// AOK-DRIVER-001: is `path` owned by a principal we trust to have staged
/// an elevated-install job — the current (elevated) user, the
/// Administrators group, or SYSTEM? Used by the helper to reject files a
/// lower-privilege process may have planted in the work dir. Returns
/// `Err` on a security-API failure so the caller can decide (it treats
/// that as a logged soft-pass, since the catalog/instance/INF
/// re-validation is the primary defence).
pub fn file_owner_is_trusted(path: &std::path::Path) -> Result<bool, String> {
    use windows_sys::Win32::Foundation::LocalFree;
    use windows_sys::Win32::Security::Authorization::{GetNamedSecurityInfoW, SE_FILE_OBJECT};
    use windows_sys::Win32::Security::{
        IsWellKnownSid, WinBuiltinAdministratorsSid, WinLocalSystemSid, OWNER_SECURITY_INFORMATION,
        PSID,
    };

    let path_w = wide_null(&path.to_string_lossy());
    let mut owner: PSID = null_mut();
    let mut security_descriptor = null_mut();
    let rc = unsafe {
        GetNamedSecurityInfoW(
            path_w.as_ptr(),
            SE_FILE_OBJECT,
            OWNER_SECURITY_INFORMATION,
            &mut owner,
            null_mut(),
            null_mut(),
            null_mut(),
            &mut security_descriptor,
        )
    };
    if rc != 0 {
        return Err(format!("GetNamedSecurityInfoW failed: Win32 error {}", rc));
    }
    if owner.is_null() {
        unsafe { LocalFree(security_descriptor as _) };
        return Err("GetNamedSecurityInfoW returned a null owner SID".to_string());
    }

    let admins = unsafe { IsWellKnownSid(owner, WinBuiltinAdministratorsSid) } != 0;
    let system = unsafe { IsWellKnownSid(owner, WinLocalSystemSid) } != 0;
    let is_me = current_process_user_owns(owner);

    unsafe { LocalFree(security_descriptor as _) };
    Ok(admins || system || is_me)
}

/// True when `owner` equals the current process token's user SID.
fn current_process_user_owns(owner: windows_sys::Win32::Security::PSID) -> bool {
    use windows_sys::Win32::Foundation::{CloseHandle, HANDLE};
    use windows_sys::Win32::Security::{EqualSid, GetTokenInformation, TokenUser, TOKEN_QUERY, TOKEN_USER};
    use windows_sys::Win32::System::Threading::{GetCurrentProcess, OpenProcessToken};

    unsafe {
        let mut token: HANDLE = null_mut();
        if OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &mut token) == 0 {
            return false;
        }
        let mut needed: u32 = 0;
        // First call sizes the buffer (expected to "fail" with the size in `needed`).
        GetTokenInformation(token, TokenUser, null_mut(), 0, &mut needed);
        if needed == 0 {
            CloseHandle(token);
            return false;
        }
        let mut buf = vec![0u8; needed as usize];
        let ok = GetTokenInformation(
            token,
            TokenUser,
            buf.as_mut_ptr() as *mut _,
            needed,
            &mut needed,
        );
        CloseHandle(token);
        if ok == 0 {
            return false;
        }
        let token_user = &*(buf.as_ptr() as *const TOKEN_USER);
        EqualSid(owner, token_user.User.Sid) != 0
    }
}

fn read_multi_sz(info_set: HDEVINFO, info: &SP_DEVINFO_DATA, property: u32) -> Vec<String> {
    let mut required: u32 = 0;
    let mut reg_type: u32 = 0;
    let ok = unsafe {
        SetupDiGetDeviceRegistryPropertyW(
            info_set,
            info,
            property,
            &mut reg_type,
            null_mut(),
            0,
            &mut required,
        )
    };
    if ok == 0 && unsafe { GetLastError() } != ERROR_INSUFFICIENT_BUFFER {
        return Vec::new();
    }
    if required == 0 {
        return Vec::new();
    }
    let mut buf = vec![0u8; required as usize];
    if unsafe {
        SetupDiGetDeviceRegistryPropertyW(
            info_set,
            info,
            property,
            &mut reg_type,
            buf.as_mut_ptr(),
            buf.len() as u32,
            &mut required,
        )
    } == 0
    {
        return Vec::new();
    }
    if reg_type != REG_MULTI_SZ {
        return Vec::new();
    }
    // Convert UTF-16 multi-string to Vec<String>.
    let chars: Vec<u16> = buf
        .chunks_exact(2)
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .collect();
    let mut out = Vec::new();
    let mut start = 0usize;
    for (i, &c) in chars.iter().enumerate() {
        if c == 0 {
            if i == start {
                break;
            }
            out.push(String::from_utf16_lossy(&chars[start..i]));
            start = i + 1;
        }
    }
    out
}

struct DeviceInfoSetGuard(HDEVINFO);
impl Drop for DeviceInfoSetGuard {
    fn drop(&mut self) {
        unsafe {
            SetupDiDestroyDeviceInfoList(self.0);
        }
    }
}

pub fn run_elevated_helper(helper_path: &Path, job_path: &Path) -> Result<i32, String> {
    let helper = helper_path.canonicalize().map_err(|e| {
        format!(
            "could not canonicalize helper path {:?}: {}",
            helper_path, e
        )
    })?;
    let job = job_path.canonicalize().map_err(|e| {
        format!(
            "could not canonicalize helper job path {:?}: {}",
            job_path, e
        )
    })?;

    let verb = wide_null("runas");
    let file = wide_null(&helper.to_string_lossy());
    let params = wide_null(&format!("--job \"{}\"", job.to_string_lossy()));

    unsafe {
        let mut exec = zeroed::<SHELLEXECUTEINFOW>();
        exec.cbSize = size_of::<SHELLEXECUTEINFOW>() as u32;
        exec.fMask = SEE_MASK_NOCLOSEPROCESS;
        exec.lpVerb = verb.as_ptr();
        exec.lpFile = file.as_ptr();
        exec.lpParameters = params.as_ptr();
        exec.nShow = SW_SHOWNORMAL;

        if ShellExecuteExW(&mut exec) == 0 {
            // ERROR_CANCELLED (1223) is the user clicking "No" on the
            // UAC consent prompt. That's an everyday outcome, not a
            // bug, so surface it as a clear message rather than an
            // opaque Win32 code.
            const ERROR_CANCELLED: u32 = 1223;
            let err = GetLastError();
            if err == ERROR_CANCELLED {
                return Err(
                    "Driver install cancelled — the elevation prompt was declined.".to_string(),
                );
            }
            return Err(format!(
                "ShellExecuteExW(runas) failed for {:?}: Win32 error {}",
                helper, err
            ));
        }

        let process = OwnedHandle(exec.hProcess);
        let wait = WaitForSingleObject(process.0, 120_000);
        if wait == WAIT_TIMEOUT {
            return Err("aokie-driver-helper timed out after 120 seconds".to_string());
        }
        if wait == WAIT_FAILED {
            return Err(format!(
                "WaitForSingleObject failed for aokie-driver-helper: Win32 error {}",
                GetLastError()
            ));
        }
        if wait != WAIT_OBJECT_0 {
            return Err(format!(
                "unexpected wait result from aokie-driver-helper: {}",
                wait
            ));
        }

        let mut exit_code = 1;
        if GetExitCodeProcess(process.0, &mut exit_code) == 0 {
            return Err(format!(
                "GetExitCodeProcess failed for aokie-driver-helper: Win32 error {}",
                GetLastError()
            ));
        }

        Ok(exit_code as i32)
    }
}

struct OwnedHandle(HANDLE);

impl Drop for OwnedHandle {
    fn drop(&mut self) {
        if !self.0.is_null() {
            unsafe {
                CloseHandle(self.0);
            }
        }
    }
}

fn wide_null(value: &str) -> Vec<u16> {
    value.encode_utf16().chain(std::iter::once(0)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_expected_hardware_id() {
        assert_eq!(hardware_id(0x0a5c, 0x21ec), "USB\\VID_0A5C&PID_21EC");
    }

    #[test]
    fn sanitizes_inf_strings() {
        assert_eq!(sanitize_inf_string("  Foo\n\"Bar\"\tBaz  "), "Foo Bar Baz");
        assert_eq!(sanitize_inf_string("\n\t"), "Aokie Bluetooth Dongle");
    }

    #[test]
    fn inf_contains_selected_device_and_winusb_sections() {
        let package =
            WinusbPackage::new(0x0a5c, 0x21ec, "BCM20702A0").with_driver_ver("04/26/2026,2.2.0.0");
        let inf = package.render_inf();
        assert!(inf.contains("USB\\VID_0A5C&PID_21EC"));
        assert!(inf.contains("Include=winusb.inf"));
        assert!(inf.contains("Needs=WINUSB.NT"));
        assert!(inf.contains(AOKIE_INTERFACE_GUID));
        assert!(inf.contains("BCM20702A0"));
        // Multi-arch sections so x86 / amd64 / arm64 hosts all match.
        assert!(inf.contains("[AokieDevices.NTx86]"));
        assert!(inf.contains("[AokieDevices.NTamd64]"));
        assert!(inf.contains("[AokieDevices.NTarm64]"));
        // Class registration so the dongle shows up under "Universal Serial
        // Bus devices" rather than as an unnamed class on first install.
        assert!(inf.contains("[ClassInstall32]"));
        assert!(inf.contains("Universal Serial Bus devices"));
        assert!(inf.contains("CatalogFile=aokie_winusb_bluetooth.cat"));
        assert!(inf.contains("DriverVer=04/26/2026"));
        // Explicit AddService + ServiceInstall sections (not just
        // Needs=WINUSB.NT.Services) so the package looks "complete" to
        // PnP on re-evaluation post-replug. Without these, our INF
        // gets de-ranked vs Microsoft-signed BTHUSB on the next plug-in
        // and the binding "evaporates" — matching what users
        // hit in the wild.
        assert!(inf.contains("AddService=WinUSB,0x00000002,WinUSB_ServiceInstall"));
        assert!(inf.contains("[WinUSB_ServiceInstall]"));
        assert!(inf.contains("ServiceBinary=%12%\\WinUSB.sys"));
        // KMDF binding declaration. WinUSB.sys is built on KMDF; PnP's
        // re-pick logic on Win10/11 wants this section present even
        // though we inherit the actual library content via Needs.
        assert!(inf.contains("[WinUSB_Install.Wdf]"));
        assert!(inf.contains("KmdfService=WINUSB, WinUsb_Install"));
        assert!(inf.contains("KmdfLibraryVersion="));
    }

    #[test]
    fn describes_setup_errors_actionably() {
        // Spot-check that the cat-related codes return guidance, not
        // just hex. ERROR_FILE_HASH_NOT_IN_CATALOG was the one Win10/11
        // hit hardest before we shipped self-signed cats.
        let m = describe_setup_error(0xE000_024B);
        assert!(m.contains("CAT") && m.contains("hash"), "got {:?}", m);

        let m = describe_setup_error(5);
        assert!(m.contains("administrator"), "got {:?}", m);

        // Unknown codes still get the raw hex tail so a developer can
        // search MSDN.
        let m = describe_setup_error(0xDEAD_BEEF);
        assert!(m.contains("0xdeadbeef"), "got {:?}", m);
    }

    #[test]
    fn default_driver_ver_uses_today() {
        let package = WinusbPackage::new(0x0a5c, 0x21ec, "BCM20702A0");
        let inf = package.render_inf();
        // Today's local date gets folded into DriverVer's revision so
        // each daily build supersedes older driver-store copies.
        let today = chrono::Local::now().naive_local().date();
        let expected_year = format!("/{}", today.year());
        assert!(
            inf.contains(&expected_year),
            "DriverVer should embed today's year: inf was {:?}",
            inf
        );
    }
}
