//! Linux counterpart to `aokie_dongle` (which is Windows-only).
//!
//! Where the Windows `aokie_dongle` ships an INF + cat + cert bundle so
//! WinUSB binds to the dongle, on Linux every modern kernel already
//! exposes raw USB devices via libusb. The Linux pairing UX therefore
//! reduces to two questions:
//!
//!   1. **Can the user's account talk to the dongle?** Default udev
//!      rules give /dev/bus/usb nodes mode 0660 owned by root:plugdev
//!      — accounts not in the plugdev group can't open the device. We
//!      ship a udev rule that grants access to a specific VID:PID set
//!      (matching the dongle catalog) so the desktop user doesn't have
//!      to chmod 666 the bus.
//!
//!   2. **Is btusb holding the dongle?** The kernel's btusb driver
//!      claims interface 0 of every recognized Bluetooth dongle at
//!      plug-time. Our libusb transport detaches it on open(); the UX
//!      indicator just surfaces whether btusb is currently bound so
//!      the user can stop bluetoothd or unbind manually if needed.
//!
//! This file is the data-layer for those two — the udev rule renderer
//! (no I/O — the caller decides whether to write to disk via pkexec
//! or just show the rendered rule for manual install) and a small
//! "is the dongle accessible" probe.
//!
//! Tauri command surface is added in Phase L5b.

#![cfg(target_os = "linux")]
#![allow(dead_code)] // Phase L5a — Tauri command exposure follows in L5b.

// `DongleId` and the catalog live in `aokie_dongle_catalog` so the
// Windows WinUSB UX, the Linux udev path, and the frontend all
// resolve "is this an Aokie dongle?" against the same list. The
// re-exports here keep this module's public API stable for callers
// that already imported `aokie_dongle_linux::DongleId`.
pub use aokie_core::dongle_catalog::{DongleId, DEFAULT_CATALOG};

/// Render `/etc/udev/rules.d/99-aokie.rules` for a given catalog.
///
/// Default mechanism is `TAG+="uaccess"` only — systemd-logind grants
/// the device to whichever user is logged in at the local console
/// (R12-#11). On a single-user desktop that's exactly what we want:
/// the desktop user gets the dongle, headless / non-console users
/// don't. Aokie Bluetooth dongles aren't shared resources where you
/// want every account to be able to open them.
///
/// `permissive=true` adds `MODE="0666"` to each rule so any local
/// account can open the dongle (the previous default). Operators on
/// systems without working logind — kiosk distros, ssh-only headless
/// boxes, Wayland sessions where uaccess doesn't fire reliably — can
/// flip the `AOKIE_UDEV_PERMISSIVE=1` env on the frontend's "render
/// rule" call to fall back to the wider mode. Documented as a
/// belt-and-braces escape hatch, not the recommended path.
pub fn render_udev_rule(catalog: &[DongleId], permissive: bool) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Aokie. Edit /etc/udev/rules.d/99-aokie.rules\n");
    out.push_str("# to revoke access; reload with `sudo udevadm control --reload-rules`.\n");
    out.push_str("#\n");
    out.push_str("# These rules grant the desktop user permission to open the\n");
    out.push_str("# Aokie Bluetooth dongle directly via libusb. They do NOT\n");
    out.push_str("# unbind btusb — the app does that per-session.\n");
    out.push_str("#\n");
    if permissive {
        out.push_str("# Permissive mode: rules include MODE=\"0666\" so any local\n");
        out.push_str("# account can open the dongle. Use only on kiosk / headless /\n");
        out.push_str("# non-logind systems where uaccess doesn't fire.\n");
    } else {
        out.push_str("# Standard mode: TAG+=\"uaccess\" hands the device to the\n");
        out.push_str("# user logged in at the local console (via systemd-logind).\n");
        out.push_str("# To grant access to additional accounts, regenerate the\n");
        out.push_str("# rule with permissive mode (MODE=0666) — see Aokie's\n");
        out.push_str("# Pairing → Advanced disclosure.\n");
    }
    out.push('\n');
    for id in catalog {
        if permissive {
            out.push_str(&format!(
                "SUBSYSTEM==\"usb\", ATTR{{idVendor}}==\"{:04x}\", \
                 ATTR{{idProduct}}==\"{:04x}\", MODE=\"0666\", \
                 TAG+=\"uaccess\"\n",
                id.vid, id.pid
            ));
        } else {
            out.push_str(&format!(
                "SUBSYSTEM==\"usb\", ATTR{{idVendor}}==\"{:04x}\", \
                 ATTR{{idProduct}}==\"{:04x}\", TAG+=\"uaccess\"\n",
                id.vid, id.pid
            ));
        }
    }
    out
}

/// Probe whether the standard udev rule is already in place. Useful
/// for the pairing UI's "rule installed" badge.
pub fn udev_rule_path() -> &'static str {
    "/etc/udev/rules.d/99-aokie.rules"
}

#[cfg(test)]
mod tests {
    use super::*;
    use aokie_core::dongle_catalog::DongleCompatTier;

    #[test]
    fn render_udev_rule_emits_one_line_per_catalog_entry() {
        let catalog = &[
            DongleId {
                vid: 0x0a5c,
                pid: 0x21e8,
                tier: DongleCompatTier::Certified,
            },
            DongleId {
                vid: 0x0bda,
                pid: 0x8771,
                tier: DongleCompatTier::Beta,
            },
        ];
        let rule = render_udev_rule(catalog, false);
        let lines: Vec<&str> = rule
            .lines()
            .filter(|l| l.starts_with("SUBSYSTEM"))
            .collect();
        assert_eq!(lines.len(), 2);
        assert!(lines[0].contains("0a5c"));
        assert!(lines[0].contains("21e8"));
        assert!(lines[1].contains("0bda"));
        assert!(lines[1].contains("8771"));
    }

    #[test]
    fn standard_mode_uses_uaccess_only_no_world_rw() {
        let rule = render_udev_rule(DEFAULT_CATALOG, false);
        assert!(rule.contains("TAG+=\"uaccess\""));
        assert!(
            !rule.contains("MODE=\"0666\""),
            "standard mode must not grant world-rw — that's the permissive override"
        );
    }

    #[test]
    fn permissive_mode_adds_world_rw_for_kiosk_setups() {
        let rule = render_udev_rule(DEFAULT_CATALOG, true);
        assert!(rule.contains("TAG+=\"uaccess\""));
        assert!(rule.contains("MODE=\"0666\""));
    }

    #[test]
    fn render_udev_rule_starts_with_a_doc_comment_block() {
        let rule = render_udev_rule(DEFAULT_CATALOG, false);
        let first = rule.lines().next().unwrap();
        assert!(first.starts_with("# Generated by Aokie"));
    }
}
